### ISSUE TITLE
Segmentation fault occurred when tuning the image config

### ISSUE THREAD

**Issue by Kanazawanaoaki** [HiroIshida/mohou_ros_utils#11]
When I followed [Tuning the image config](https://github.com/HiroIshida/mohou_ros_utils#tuning-the-image-config )'s directions and pressed "q", a segmentation fault occurred and image_config.yam was not saved.  
```
$ rosrun mohou_ros tune_image_filter.py -pn blue_box_continue_long
Failed to load Python extension for LZ4 support. LZ4 compression will not be available.
initialize window
Segmentation fault (コアダンプ)
```

**Comment by Kanazawanaoaki** [comment]
When I try [`example/hsv_blur_crop.py`](https://github.com/HiroIshida/tunable_filter/blob/f9e8a6ebb1bff63dde058764f0b82e3f4ba1e068/example/hsv_blur_crop.py ) of https://github.com/HiroIshida/tunable_filter.  
Segmentation fault did not occur and the config was saved.
```
$ python3 example/hsv_blur_crop.py --tune
initialize window
press q to finish tuning
{'CropResizer': {'x_max': 379, 'x_min': 0, 'y_max': 505, 'y_min': 0},
 'GaussianBlurFilter': {'kernel_width': 10},
 'HSVLogicalFilter': {'h_max': 255,
                      'h_min': 0,
                      's_max': 255,
                      's_min': 0,
                      'v_max': 255,
                      'v_min': 0},
 'ResolutionChangeResizer': {'resol': 148}}
```
Also, if I try it with the comment out, I find that the Segmentation fault occurs in https://github.com/HiroIshida/mohou_ros_utils/blob/097f525943425f020e15f86ce41b5c273d857e2b/scripts/tune_image_filter.py#L43  
Is it a problem with the data?  
Just in case, main_config.yaml used is as follows.
```
topic: 
    AngleVector:
        name: /joint_states
        rosbag: True
        use: True
    RGBImage: 
        name: /kinect_head/rgb/image_rect_color/compressed
        rosbag: True
        use: True
    DepthImage: 
        name: /kinect_head/depth_registered/image/compressedDepth
        rosbag: True
        use: False
    GripperState:
        name: /r_gripper_controller/state
        rosbag: True
        use: True

control_joints:
    - r_shoulder_pan_joint 
    - r_shoulder_lift_joint
    - r_upper_arm_roll_joint
    - r_elbow_flex_joint
    - r_forearm_roll_joint
    - r_wrist_flex_joint 
    - r_wrist_roll_joint
    - r_gripper_joint
```
